// module.exports={
//   congfigureWebpack:{
//     resolve:{
//         alias:{
//           'assets':'@/assets',
//           'common':'@/common',
//           'components':'@/compoents',
//           'network':'@network',
//           'views':'@views'
//         }
//     }
//   }
// }
